# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 07:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicbox', '0021_song_overall_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='song',
            name='file_size',
        ),
    ]
